import React from 'react'
import ReactDOM from 'react-dom/client'
import reportWebVitals from './reportWebVitals'
import {createBrowserRouter, RouterProvider} from 'react-router-dom'
import { Login } from './components/auth/Login'